---
kind: pipeline
name: Build and Push container image

steps:
  - name: Push image to local registry.
    image: plugins/docker
    settings:
      registry: registry.battlenet.work
      repo: registry.battlenet.work/burnedvpn/directorylister
      auto_tag: true
      build_args_from_env: [ DRONE_TAG ]

trigger:
  event: [ tag ]
