---
kind: pipeline
name: Build and push Directory Lister container image

steps:
  - name: Push image to local registry.
    image: plugins/docker
    settings:
      repo: registry.battlenet.work/burnedvpn/directorylister
      auto_tag: true
      build_args_from_env: [ DRONE_TAG ]

  - name: Push image to Dockerhub. 
    image: plugins/docker
    settings:
      repo: burnedvpn/directorylister
      username: burnedvpn
      password:
        from_secret: dockerhub_password
      auto_tag: true
      build_args_from_env: [ DRONE_TAG ]

trigger:
  event: [ tag ]

---
kind: secret
name: dockerhub_password
get:
  path: secrets/data/users
  name: burnedvpn@dockerhub