---
kind: pipeline
name: Build and push Directory Lister container image

steps:
  - name: Push image to local registry.
    image: plugins/docker
    settings:
      auto_tag: true
      build_args_from_env: [ DRONE_TAG ]
      repo: registry.battlenet.work/burnedvpn/directorylister

trigger:
  event: [ push, tag ]